package com.backend.authsystem.authentication.enums;

public enum PermissionEnum {

    //User-level permissions

    //profile-level
    PROFILE_VIEW, //(USER)
    PROFILE_UPDATE, //(USER)

    // account-level
    ACCOUNT_VIEW, //(USER)
    PASSWORD_CHANGE, //(USER)

    // lecturer-level
    // course
    COURSE_CREATE, //(LECTURER)
    COURSE_UPDATE, //(LECTURER)
    COURSE_PUBLISH, //(LECTURER)
    COURSE_OPEN_ENROLLMENT, //(LECTURER)
    COURSE_CLOSE_ENROLLMENT, //(LECTURER)
    COURSE_START, //(LECTURER)
    COURSE_COMPLETE, //(LECTURER)
    COURSE_ARCHIVE, //(STUDENT)
    COURSE_VIEW, //(LECTURER, STUDENT)
    COURSE_VIEW_ALL, //(LECTURER, STUDENT)


    // student-level
    COURSE_ENROLL,
    ASSIGNMENT_VIEW,
    ASSIGNMENT_SUBMIT,
    COURSE_MATERIAL_VIEW,
    CLASS_FEEDBACK_SUBMIT,
    GENERAL_ANNOUNCEMENT_VIEW,


    // course rep-level
    CLASS_ANNOUNCEMENT_VIEW,
    CLASS_ANNOUNCEMENT_RELAY,
    CLASS_FEEDBACK_COLLECT,
    CLASS_FEEDBACK_FORWARD,

    // materials
    COURSE_MATERIAL_CREATE,
    COURSE_MATERIAL_UPDATE,
    COURSE_MATERIAL_DELETE,

    ASSIGNMENT_CREATE,
    ASSIGNMENT_GRADE,
    CLASS_FEEDBACK_VIEW,
    CLASS_ANNOUNCEMENT_CREATE,

//    ENROLLED STUDENTS_VIEW,


    // admin-level (system)
    ROLE_ASSIGN, //(ADMIN)
    PERMISSION_ASSIGN, //(ADMIN)
    USER_MANAGE

}
